<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-07T16:51:19 IST" name="Default suite" finished-at="2025-03-07T16:52:24 IST" duration-ms="64744">
    <groups>
    </groups>
    <test started-at="2025-03-07T16:51:19 IST" name="Default test" finished-at="2025-03-07T16:52:24 IST" duration-ms="64744">
      <class name="HumanResource.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:19 IST" name="setup" finished-at="2025-03-07T16:51:21 IST" duration-ms="1473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:21 IST" name="startTest" finished-at="2025-03-07T16:51:21 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void HumanResource.LoginTest.loginTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:21 IST" name="loginTest" data-provider="getLoginData" finished-at="2025-03-07T16:51:31 IST" duration-ms="10306" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:31 IST" name="tearDown" finished-at="2025-03-07T16:51:32 IST" duration-ms="530" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SUCCESS method=LoginTest.loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:32 IST" name="loginTest" data-provider="getLoginData" finished-at="2025-03-07T16:51:46 IST" duration-ms="14162" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[HR_Manager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[HR@2024]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login should not be successful for invalid credentials!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login should not be successful for invalid credentials!
at HumanResource.LoginTest.loginTest(LoginTest.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:32 IST" name="startTest" finished-at="2025-03-07T16:51:32 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void HumanResource.LoginTest.loginTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:46 IST" name="tearDown" finished-at="2025-03-07T16:51:46 IST" duration-ms="135" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:46 IST" name="loginTest" data-provider="getLoginData" finished-at="2025-03-07T16:52:02 IST" duration-ms="15523" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Data_Manager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Emp@12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login should not be successful for invalid credentials!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login should not be successful for invalid credentials!
at HumanResource.LoginTest.loginTest(LoginTest.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:51:46 IST" name="startTest" finished-at="2025-03-07T16:51:46 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void HumanResource.LoginTest.loginTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:02 IST" name="tearDown" finished-at="2025-03-07T16:52:02 IST" duration-ms="184" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:02 IST" name="startTest" finished-at="2025-03-07T16:52:02 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void HumanResource.LoginTest.loginTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:02 IST" name="loginTest" data-provider="getLoginData" finished-at="2025-03-07T16:52:08 IST" duration-ms="6375" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:08 IST" name="tearDown" finished-at="2025-03-07T16:52:08 IST" duration-ms="37" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SUCCESS method=LoginTest.loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:08 IST" name="startTest" finished-at="2025-03-07T16:52:08 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void HumanResource.LoginTest.loginTest(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:08 IST" name="loginTest" data-provider="getLoginData" finished-at="2025-03-07T16:52:23 IST" duration-ms="15109" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Operation_Manager]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[WrongPass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login should not be successful for invalid credentials!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login should not be successful for invalid credentials!
at HumanResource.LoginTest.loginTest(LoginTest.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:23 IST" name="tearDown" finished-at="2025-03-07T16:52:24 IST" duration-ms="149" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest(java.lang.String,java.lang.String)[pri:0, instance:HumanResource.LoginTest@4e50c791] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:HumanResource.LoginTest@4e50c791]" started-at="2025-03-07T16:52:24 IST" name="cleanup" finished-at="2025-03-07T16:52:24 IST" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- HumanResource.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
